server:
  port: 8082

spring:
  application:
    name: driver-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/driver_db}
    username: ${SPRING_DATASOURCE_USERNAME:taxi}
    password: ${SPRING_DATASOURCE_PASSWORD:taxi}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: driver-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "vn.taxi.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: vn.taxi.driver.event.UserCreatedEvent

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
